# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Package

on:
  release:
    types: [created]

jobs:
  build-darwin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun build --compile --target=bun-darwin-arm64 ./src/queryblast.ts

  publish-darwin-gpr:
    needs: build-darwin
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          registry-url: https://npm.pkg.github.com/
      - run: bun publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
