# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Create alpha release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-darwin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Build
        run: |
          bun install
          bun build --compile --target=bun-darwin-arm64 ./src/queryblast.ts
      - name: Create Alpha Release
        id: create_alpha_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.ref }}-alpha
          release_name: Alpha release ${{ github.ref }}
          draft: false
          prerelease: true
      - name: Upload Alpha Release Asset
        id: upload-alpha-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_alpha_release.outputs.upload_url }} 
          asset_path: ./queryblast
          asset_name: queryblast-${{ github.sha }}-alpha
          asset_content_type: application/octet-stream
